src/google/cloud/ndb/tasklets.py
tests/conftest.py
tests/unit/test_key.py
tests/unit/test_tasklets.py

Makes sure that inside of a tasklet the context doesn't change.

NDB: Consistent context inside of tasklets.

---

src/google/cloud/ndb/model.py
src/google/cloud/ndb/query.py
tests/unit/test_model.py
tests/unit/test_query.py

This was https://github.com/googleapis/google-cloud-python/pull/7239 and merged after the fork. Porting this over.

NDB: Query Constructor

---

src/google/cloud/ndb/_retry.py
src/google/cloud/ndb/_transaction.py
tests/unit/test__retry.py
tests/unit/test__transaction.py

Add retry for transactions.

---

src/google/cloud/ndb/_datastore_query.py
tests/system/conftest.py
tests/system/test_query.py
tests/unit/test__datastore_query.py

Ancestor queries

---

src/google/cloud/ndb/_retry.py
tests/unit/test__retry.py

Include a couple of GRPC transient errors in retry.

---

src/google/cloud/ndb/model.py
src/google/cloud/ndb/query.py
tests/unit/test_model.py
tests/unit/test_query.py

As discussed in Hangouts, create new PorpertyOrder class to store property name and sort direction.

improved mechanism for defining and storing query order

---

src/google/cloud/ndb/_datastore_query.py
src/google/cloud/ndb/query.py
tests/system/test_query.py
tests/unit/test__datastore_query.py
tests/unit/test_query.py

Implement filters for queries.

---

MIGRATION_NOTES.md
src/google/cloud/ndb/metadata.py
tests/system/test_metadata.py
tests/unit/test_metadata.py

This completes metadata functionality, including system tests. Note that it can't be merged as is, because I need the sphinx change from PR #56 to be merged before, and that means I will have to rebase this one.
Sorry for the long PR, should be the last of the "mega" PRs.

Metadata query

---

src/google/cloud/ndb/_datastore_query.py
src/google/cloud/ndb/query.py
tests/system/test_query.py
tests/unit/test__datastore_query.py
tests/unit/test_query.py

Query offset and limit

---

README.md

Add clarification on purpose of project, link to Py2 version and release status.

Remove all stale info from README and clarify status

---

MIGRATION_NOTES.md
src/google/cloud/ndb/__init__.py
src/google/cloud/ndb/_datastore_query.py
src/google/cloud/ndb/query.py
tests/system/test_query.py
tests/unit/test__datastore_query.py
tests/unit/test_query.py

Query fetch has been refactored to work on top of query iterators. 
Sorry about the size. Became apparent once I started working on it that some refactoring would be required.

Implement query iterators.

---

src/google/cloud/ndb/_gql.py
src/google/cloud/ndb/exceptions.py
src/google/cloud/ndb/model.py
src/google/cloud/ndb/query.py
tests/unit/test__gql.py
tests/unit/test_model.py
tests/unit/test_query.py

We needed to port this, but not the whole thing. Took the parsing bits only simplified a bit (hopefully), and adjusted for our NDB query workings.

 Port GQL parser and add GQL support for query

---

tests/system/__init__.py
tests/system/test_metadata.py
tests/system/test_query.py

Applying a liberal application of ``eventually`` to try to wait for
eventual consistency in system tests.

Make system tests fail less often.

---

tests/system/test_query.py

Make sure the eventually tests are testing that *all* entities have been
created before running queries against them.

Yet another fix for system tests.

---

noxfile.py
src/google/cloud/ndb/_datastore_query.py
src/google/cloud/ndb/query.py
tests/system/test_query.py
tests/unit/test__datastore_query.py
tests/unit/test_query.py
tests/unit/utils.py

Query count

---

src/google/cloud/ndb/model.py
tests/system/test_crud.py
tests/unit/test_model.py

Model.get by

---

src/google/cloud/ndb/model.py
tests/unit/test_model.py

``Model.populate``, ``Model.has_complete_key``, ``Model.to_dict``.

Three easy Model methods.

---

src/google/cloud/ndb/query.py

Fixes build error in docs on master branch.

Fix docs build.

---

src/google/cloud/ndb/__init__.py
src/google/cloud/ndb/model.py
tests/system/test_crud.py

Also fixes how the entity's class is stored.

add system test for PolyModel

---

src/google/cloud/ndb/model.py
tests/system/test_crud.py
tests/unit/test_model.py

Fix key property.

---

src/google/cloud/ndb/model.py
tests/system/test_crud.py
tests/unit/test_model.py

Fixes problem from issue #139.

check for required properties before put

---

src/google/cloud/ndb/context.py
tests/unit/test_context.py

Implement ``Context.flush``

---

MIGRATION_NOTES.md
src/google/cloud/ndb/_options.py
src/google/cloud/ndb/blobstore.py
src/google/cloud/ndb/context.py
src/google/cloud/ndb/key.py
src/google/cloud/ndb/model.py
src/google/cloud/ndb/query.py

Officially deprecate everything we've said we're not going to do for beta.

Deprecations

---

src/google/cloud/ndb/_datastore_api.py
tests/unit/test__datastore_api.py

Raise an exception when storing entity with partial key without Datastore.

---

google/cloud/ndb/model.py
tests/system/test_crud.py
tests/unit/test_model.py

Problem reported first in #180.

fix error retrieving values for properties with different stored name

---

google/cloud/ndb/model.py
tests/system/test_crud.py
tests/unit/test_model.py
tests/unit/test_query.py

Add `tzinfo` to DateTimeProperty.

---

CHANGELOG.md
setup.py

This pull request was generated using releasetool.

Release v0.2.0

---

google/cloud/ndb/query.py
tests/system/test_query.py
tests/unit/test_query.py

fix: More friendly error message when using `fetch_page` with post-filters.

---

google/cloud/ndb/model.py
tests/system/test_crud.py
tests/unit/test_model.py

fix compressed and repeated properties

---

google/cloud/ndb/model.py
tests/unit/test_model.py

fix: Fix repr() for ComputedProperty

---

google/cloud/ndb/model.py
tests/system/test_crud.py

fix: Fix bug when wrapping base values.

---

google/cloud/ndb/__init__.py
google/cloud/ndb/_cache.py
google/cloud/ndb/_datastore_api.py
google/cloud/ndb/client.py
tests/system/conftest.py
tests/system/test_crud.py
tests/unit/test__cache.py
tests/unit/test__datastore_api.py
tests/unit/test_client.py

@VladNF found a bug (and the solution) that caused results from calls to
the global cache to get out of synch with the futures waiting on them.
Fixes #294.

fix: Fix bug with the _GlobalCacheGetBatch.

---

google/cloud/ndb/_remote.py

The wrapper, `_remote.RemoteCall`, added to help attach debugging into
to gRPC calls, inadvertantly introduced a race condition between the
gRPC thread and the NDB thread, where the gRPC thread might call
`RemoteCall._finish` *during* a call to `RemoteCall.add_done_callback`.
The solution, here, is to turn `RemoteCall.add_done_callback` into a
direct pass-through to `grpc.Future.add_done_callback` on the wrapped
future. The callback which is eventually executed in the gRPC thread,
only pushes the finished RPC onto a `queue.Queue` which is eventually
consumed by the event loop running in the NDB thread.
Fixes #302.

fix: fix race condition in remote calls

---

.repo-metadata.json

Update .repo-metadata to reflect latest release level (GA)

docs: update release_level

---

google/cloud/ndb/model.py
tests/system/test_crud.py
tests/unit/test_model.py

fix: properly exclude from indexes non-indexed subproperties of structured properties

---

google/cloud/ndb/model.py
tests/system/test_query.py
tests/unit/test_model.py

fix: use correct name when reading legacy structured properties with names

---

google/cloud/ndb/model.py
tests/system/test_crud.py
tests/unit/test_model.py

…when converting from base type
refs #359

fix: check for legacy local structured property values

---

google/cloud/ndb/model.py
tests/unit/test_model.py

fix: empty Entities for optional LocalStructuredProperty fields 

---

google/cloud/ndb/model.py
tests/unit/test_model.py

fix: add missing _get_for_dict method

---

google/cloud/ndb/_gql.py
tests/system/test_query.py
tests/unit/test__gql.py

feature: add gql functions to improve compatibility

---

google/cloud/ndb/query.py

docs: show no longer supported options as deprecated

---

google/cloud/ndb/model.py
tests/system/test_crud.py
tests/system/test_metadata.py
tests/system/test_query.py
tests/unit/test_model.py

fix: do not allow empty key parts for key constructor in namespaced model

---

google/cloud/ndb/model.py

fix: support same options in model.query as query

---

google/cloud/ndb/model.py
tests/system/test_crud.py
tests/unit/test_model.py

Feature: Improve custom validators

---

synth.py

chore: enable context-aware commits

---

synth.py

build: get kokoro file generation in sync with synthtool

---

google/cloud/ndb/query.py
tests/unit/test_query.py

fix: more should be boolean in fetch_page call

---

google/cloud/ndb/_datastore_api.py
tests/system/test_crud.py

fix: fix `NotImplementedError` for `get_or_insert` inside a transaction

---

google/cloud/ndb/key.py
google/cloud/ndb/model.py
tests/unit/test_model.py

fix: make sure datastore key constructor never gets None in a pair

---

google/cloud/ndb/_retry.py
tests/unit/test__retry.py

fix: retry grpc `UNKNOWN` errors

---

google/cloud/ndb/_datastore_query.py
google/cloud/ndb/query.py
tests/system/test_query.py
tests/unit/test__datastore_query.py
tests/unit/test_query.py

feat: allow `Query.fetch_page` for queries with post filters

---

google/cloud/ndb/model.py
tests/system/test_misc.py

During deserialization from Datastore, since NDB properties can be
arbitrarily mapped to Datastore properties of different names, it is
possible for a Datastore entity to have a property with the same name as
an NDB property, but that isn't the Datastore property mapped to that
NDB property. This fix prevents the unmapped Datastore property from
accidentally clobbering the NDB property of the same name.
Fixes #461.

fix: ignore datastore properties that are not mapped to NDB properties

---

google/cloud/ndb/_legacy_entity_pb.py
google/cloud/ndb/_legacy_protocol_buffer.py
google/cloud/ndb/model.py
tests/unit/test__legacy_entity_pb.py
tests/unit/test_model.py

@chrisrossi this is almost finished, but needs more test coverage. I put it up here so you can hopefully take a look before today's meeting. I tried to get rid of all superfluous code (a lot), but it's still big.

feature: add compatibility layer for legacy protobuffer implementation

---

google/cloud/ndb/query.py
tests/system/conftest.py
tests/system/test_query.py
tests/unit/test_query.py

fix: properly handle explicitly passing default namespace

---

google/cloud/ndb/global_cache.py
tests/system/test_misc.py
tests/unit/test_global_cache.py

fix: fix concurrency bug in redis cache implementation

---

google/cloud/ndb/_gql.py
google/cloud/ndb/_legacy_protocol_buffer.py
google/cloud/ndb/model.py
google/cloud/ndb/query.py
google/cloud/ndb/utils.py
tests/system/test_query.py
tests/unit/test__gql.py
tests/unit/test__legacy_entity_pb.py
tests/unit/test_query.py

build: remove warnings from tests

---

google/cloud/ndb/tasklets.py
noxfile.py
tests/unit/test__retry.py
tests/unit/test_tasklets.py
tests/unit/utils.py

fix: fix exception handling bug in tasklets

---

google/cloud/ndb/key.py

docs: fix type hint for urlsafe

---

CONTRIBUTING.rst
README.md
noxfile.py
setup.py

build: support python 3.8 and 3.9

---

google/cloud/ndb/_cache.py
google/cloud/ndb/_datastore_api.py
google/cloud/ndb/global_cache.py
tests/unit/test__cache.py
tests/unit/test_global_cache.py

feat: fault tolerance for global caches

---

google/cloud/ndb/model.py

docs: fix typo in example code

---

google/cloud/ndb/query.py

docs: fix return type in fetch docstring

---

tests/unit/test_model.py

fix: fix failing unit test

---

google/cloud/ndb/_legacy_entity_pb.py
tests/system/test_misc.py

fix: correctly decode falsy values in legacy protocol buffers

---

.github/CODEOWNERS

This should allow me to merge PRs again.

chore: add yoshi-python to CODEOWNERS
