googleapis/python-ndb

src/google/cloud/ndb/_datastore_api.py
src/google/cloud/ndb/_eventloop.py
tests/unit/test__datastore_api.py

This is just an indirection to make debugging easier. It's impossible to
tell from the futures handed back by grpc what the actual call was. This
fixes that.

Introduce RemoteCall class.

---

.appveyor.yml
.circleci/config.yml
CONTRIBUTING.rst
noxfile.py
setup.py

As discussed in PR #24, drop Python 3.5 support to make it easier to use newer language features.

drop python 3.5 support

---

MIGRATION_NOTES.md
src/google/cloud/ndb/model.py
tests/system/test_system.py
tests/unit/test_model.py
tests/unit/test_polymodel.py

Fixes issue #32.
Note that strings were not being stored as base64.
That's just how the Google Console represents binary data in the UI.
Strings were being stored as binary data, however, and that has been
fixed. Strings were also being stored as binary data in legacy NDB.
Legacy databases with strings stored as binary will still work with this
version of NDB as we can handle getting ``bytes`` or ``str`` from
``google.cloud.datastore``.

Store strings as strings in Datastore.

---

noxfile.py
src/google/cloud/ndb/_datastore_query.py
src/google/cloud/ndb/query.py
tests/system/__init__.py
tests/system/conftest.py
tests/system/test_crud.py
tests/system/test_query.py
tests/unit/test__datastore_query.py
tests/unit/test_query.py

This is the bare minimum necessary to run the simplest query possible:
all of the entities of a given kind.

Wire up queries to Datastore.

---

src/google/cloud/ndb/_datastore_query.py
tests/system/test_query.py
tests/unit/test__datastore_query.py

Datastore has renamed `group_by` to `distinct_on`. I think, for consistency, we should do the same and leave `group_by` as an optional synonym for `distinct_on` for backwards compatibility. I didn't want to do that now, with #46 pending, as I'd probably just create conflicts. One of us can do it after both of these are merged.

Implement group_by for queries.

---

src/google/cloud/ndb/_datastore_query.py
src/google/cloud/ndb/query.py
tests/system/test_query.py
tests/unit/test_query.py

As discussed on https://github.com/googleapis/python-ndb/pull/48

Rename group_by to distinct_on, for consistency with datastore

---

src/google/cloud/ndb/_datastore_query.py
src/google/cloud/ndb/model.py
src/google/cloud/ndb/query.py
tests/system/test_query.py
tests/unit/test__datastore_query.py
tests/unit/test_model.py
tests/unit/test_query.py

This seems to have been missed when originally stubbing out ``Model``.
Took the opportunity to attempt to normalize the signatures of this
method and the ``Query`` constructor so they are largely the same. Part
of this involves moving away from catchall ``**options`` style arguments
and explicitly naming all potential arguments, as discussed in the
Hangout.
Also took this opportunity to start phasing out ``app`` in favor of
``project``. (See #2.)

Implement ``Model.query``.

---

src/google/cloud/ndb/query.py
tests/unit/test_query.py

It wasn't in Legacy NDB, it wasn't implemented here, and it looks like
we aren't going to use it.

Remove ``query.QueryOrder``.

---

src/google/cloud/ndb/_datastore_query.py
src/google/cloud/ndb/query.py
tests/unit/test_query.py

Make use of the ``default_options`` argument to the ``Query``
constructor. Make all arguments to ``Query.fetch`` explicit, and perform
the complicated dance of merging all the arguments and options to both
the ``Query`` constructor and ``Query.fetch`` into a single set of
options for passing to ``_datastore_query.fetch``.

Sort out Query options.

---

src/google/cloud/ndb/key.py
src/google/cloud/ndb/model.py
tests/system/conftest.py
tests/system/test_metadata.py
tests/unit/test_key.py
tests/unit/test_model.py

The Key constructor was not taking into account the current client namespace, which resulted in mismatched namespaces or incorrect ancestors in queries where keys are created and passed in as arguments.

Namespace management

---

tests/system/conftest.py

Try to minimize datastore errors on system tests. This does not eliminate datastore errors 100%, but it greatly decreases the rate of system test failures. It also allows back-to-back system test runs, which was impossible before.

Use random namespace on test client

---

tests/system/test_metadata.py

This fixes the problem locally for me.

add loop and timeout for properties queries on system tests

---

tests/system/conftest.py

Based on #65. 
The big advantage of using the random namespace is we can assume that entities we've asked Datastore to delete will, in fact, be deleted at some point in the future, but we don't have to wait for them anymore.

Fix system tests

---

MIGRATION_NOTES.md
src/google/cloud/ndb/query.py
tests/system/__init__.py
tests/system/test_metadata.py
tests/unit/test_query.py

State intent to not implement the `batch_size` and `prefetch_size`
attributes, as well as the `run_to_queue` method.
Fix the `fetch` and `fetch_async` method signatures to match legacy.
(`limit` can be passed as a single positional arg.)
Stub out remaining `Query` methods, so it's easier to see what remains
to be done.

Query housecleaning.

---

src/google/cloud/ndb/_eventloop.py
src/google/cloud/ndb/tasklets.py
tests/conftest.py
tests/unit/test__datastore_api.py
tests/unit/test__eventloop.py

It was found, through working query iterators, that when a TaskletFuture
calls ``_advance_tasklet`` in its done callback, if it calls it
directly, we can get a really deep call stack that eventually reaches
the limit for maximum recursion. This refactors that to add the
``_advance_tasklet`` call to the eventloop to be run soon, rather than
calling it directly, which fixes this issue by keeping the call stack
shallow. The legacy NDB code was actually already using this
indirection and I had changed it to a direct call because I couldn't
figure out why the legacy code didn't just do that, already. I knew
there was a chance that the reason would reveal itself through trial and
error, and it eventually did.
I also performed a minor refactor on the eventloop itself, adding the
``call_soon`` …

EventLoop and tasklets refactor.

---

MIGRATION_NOTES.md
src/google/cloud/ndb/model.py

Mark some Model methods as being no longer implemented as opposed to
just not implemented yet or virtual.
Update MIGRATION_NOTES to remove some outdated assumptions and include
some crucial information about establishing a runtime context.

Docs gardening.

---

src/google/cloud/ndb/_datastore_api.py
src/google/cloud/ndb/_options.py
src/google/cloud/ndb/key.py
src/google/cloud/ndb/model.py
src/google/cloud/ndb/query.py
tests/system/test_query.py
tests/unit/test__datastore_api.py
tests/unit/test__options.py
tests/unit/test_key.py
tests/unit/test_model.py
tests/unit/test_query.py

Treat "options" in a more or less uniform way for get/put/delete/query. This got more involved than I was anticipating. Sorry about the large diff.

Refactor options.

---

src/google/cloud/ndb/__init__.py
src/google/cloud/ndb/_datastore_api.py
src/google/cloud/ndb/_datastore_query.py
src/google/cloud/ndb/query.py
tests/unit/test__datastore_api.py
tests/unit/test__datastore_query.py
tests/unit/test_query.py

Legacy NDB claims to use eventual consistency by default for queries. With
this change eventual consistency is the default when there isn't a
transaction, but when there is a transaction we run a query that will
return results consistent with the current transaction.

Implement transaction for queries.

---

src/google/cloud/ndb/_datastore_api.py
src/google/cloud/ndb/model.py
tests/system/test_crud.py
tests/unit/test__datastore_api.py
tests/unit/test_model.py

Model.get or insert

---

src/google/cloud/ndb/key.py
src/google/cloud/ndb/model.py
tests/unit/test_key.py
tests/unit/test_model.py

Implement pre- and post- hooks for: ``Key.get``, ``Key.delete``,
``Model.allocate_ids``, and ``Model.put``.

Implement hooks.

---

src/google/cloud/ndb/model.py
tests/unit/test_model.py

PR for implementation of LocalStructuredProperty.
Discussion
---
I've found a different behavior between this PR and google.appengine.ext.ndb implementation.
LocalStructuredProperty inherits BlobProperty and use ```pb.SerializePartialToString()``` in Property._to_base_type both in google.appengine.ext and this.
But when I see stored properties in cloud console, one with google.appengine.ext is stored as an embedded entity value, while this implementation results to a blob value.
Maybe ```_db_set_uncompressed_meaning``` is the cause? I haven't found the exact reason.
If this difference matters, I'll dig in more.

Implement LocalStructuredProperty

---

src/google/cloud/ndb/model.py
tests/unit/test_model.py

This is almost done, but needs a final push for test coverage edge cases. I decided to remove work on LocalStructuredProperty, so that this can be merged first, and after that I can handle PR #93 without conflicts.
For now, I commented out the part where the RepeatedStructuredPropertyFilterPredicate is used. 
Note that the StructuredProperty had quite complex serialization/deserialization methods, which we do not support now, so not sure what is needed to be done there.

WIP: Model properties

---

setup.py

The URL in setup.py (and therefore the one shown on PyPI) is out of date; this should fix it.

Fix url in setup.py

---

src/google/cloud/ndb/model.py
tests/system/__init__.py
tests/system/conftest.py
tests/system/test_crud.py
tests/unit/test_model.py

Fix Structured Properties

---

src/google/cloud/ndb/client.py
tests/unit/test_client.py

In order to use the Datastore Emulator, the client needs to create an
insecure channel rather than the usual secure channel. This patch checks
for the environment variable ``DATASTORE_EMULATOR_HOST`` which indicates
the user is connecting to the Datastore Emulator, and sets the secure
flag for the client accordingly.
Fixes #110.

Support using the Datastore Emulator.

---

src/google/cloud/ndb/_options.py
src/google/cloud/ndb/context.py
src/google/cloud/ndb/key.py
src/google/cloud/ndb/model.py
tests/unit/test__options.py
tests/unit/test__transaction.py
tests/unit/test_context.py
tests/unit/test_key.py
tests/unit/test_model.py

This implements local caching for get, put, delete and transactions. It does not implement the nested "defaults" options system or turn caching on by default as in the original implementation; caching in this PR only works when use_cache=True is passed into methods.
It also alters "pre hooks" so they are run synchronously in the main thread instead of in the nested tasklet to be uniform across these methods and conform to the original implementation.
One thought: once these functions support the trio of use_datastore, use_cache and use_memcache, the matrix of options for testing could become unmanageable, and we may have to consider a complex parameterized test suite for these methods.

Local caching

---

src/google/cloud/ndb/model.py
tests/system/test_crud.py

We are porting our py27 GAE project to py37 GAE and replacing built-in services to their gcloud library counterparts.
During writing exploration tests for python-ndb we found that Expando models properties are **not loaded from datastore for existing models** and also **not saved for new ones**.
Also in the case of repeated properties that contains None values, _BaseValue(value) raising an exception.
After investigation, we made some changes in **_entity_from_ds_entity** and **_entity_to_ds_entity** functions and currently expando properties loads and saves as expected.
Please review.

ndb.Expando properties load and save

---

src/google/cloud/ndb/client.py
src/google/cloud/ndb/query.py
tests/system/conftest.py
tests/system/test_crud.py
tests/system/test_query.py
tests/unit/test_query.py

Improve usage of Datastore Emulator by not requiring credentials to be
set.
Rewrite failing system test to work around emulator discrepency with
``more_results`` field of ``QueryResultsBatch`` message.
See: https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/130
Update the ``more`` return value of ``Query.fetch_page`` to be ``False``
if an empty page has just been retrieved. This is intended to prevent
possible infinite loops in client code when using the Datastore
emulator.
Fixes #118

Fix system test under Datastore Emulator. (Fixes #118)

---

src/google/cloud/ndb/model.py
src/google/cloud/ndb/query.py
tests/system/test_crud.py
tests/system/test_query.py
tests/unit/test_model.py
tests/unit/test_query.py

When implementing structured properties the first time, I just used
Datastore's native embedded entity functionality, not realizing that NDB
had originally used dotted property names instead. (Probably GAE
Datastore didn't have embedded entities when NDB was originally
written.) The problem is that users migrating from GAE NDB can't load
entities with structured properties from their existing datastore. This
PR makes NDB backwards compatible with older, dotted name style
structured properties so that existing repositories still work with the
new NDB.
Fixes #122.

Backwards compatibility with older style structured properties.

---

src/google/cloud/ndb/model.py
tests/system/test_crud.py

Fixes bug where properties with ``_indexed=False`` were still being indexed.
Fixes #125.

Bugfix: Respect ``_indexed`` flag of properties.

---

src/google/cloud/ndb/context.py
tests/system/test_crud.py

It turns out that if you use ``__slots__`` in a ``threading.local``
subclass, it no longer works as a ``threading.local`` instance. The more
you know...
Fixes #128.

Fix thread local context.

---

src/google/cloud/ndb/model.py
tests/system/test_crud.py
tests/unit/test_model.py

The _prepare_for_put method is implemented in various properties, but not in model, and there was no call to it before put.

_prepare_for_put was not being called at entity level

---

docs/global_cache.rst
docs/index.rst
docs/spelling_wordlist.txt
src/google/cloud/ndb/__init__.py
src/google/cloud/ndb/_batch.py
src/google/cloud/ndb/_cache.py
src/google/cloud/ndb/_datastore_api.py
src/google/cloud/ndb/_options.py
src/google/cloud/ndb/_transaction.py
src/google/cloud/ndb/client.py
src/google/cloud/ndb/context.py
src/google/cloud/ndb/global_cache.py
src/google/cloud/ndb/metadata.py
src/google/cloud/ndb/model.py
src/google/cloud/ndb/tasklets.py
tests/conftest.py
tests/system/test_crud.py
tests/unit/test__batch.py
tests/unit/test__cache.py
tests/unit/test__datastore_api.py
tests/unit/test__options.py
tests/unit/test_context.py
tests/unit/test_global_cache.py
tests/unit/test_model.py

Does not include:
- Concrete implementation of ``GlobalCache`` that uses Redis. (Should only take a day or so.)
- ``use_datastore`` implementation.
Makes use of @takashi8 's surprise #130 contribution.
I still need to work on documentation, but this should be working now. This is extensive/tricky enough, that I'm likely to have overlooked something. Happy to have this one scrutinized fairly closely.

Implement Global Cache (memcache)

---

docs/conf.py
setup.py
src/google/cloud/ndb/global_cache.py
tests/system/test_crud.py
tests/unit/test_global_cache.py

Concrete implementation of ``GlobalCache`` which uses Redis. Thanks to @takashi8

RedisCache

---

MIGRATION_NOTES.md
src/google/cloud/ndb/__init__.py
src/google/cloud/ndb/context.py
src/google/cloud/ndb/model.py

Added ``RedisCache`` to top-level exports (forgot to do this earlier).
Moved ``_db_set_value()`` and ``_db_get_value()`` from the several
subclasses up to ``model.Property`` so we can not implement them in a
single place.
Changed some ``NotImplementedError``s into ``NoLongerImplementedError``s
to make explicit decision not to implement some old functionality.

Update Migration Notes.

---

src/google/cloud/ndb/tasklets.py
tests/system/test_query.py
tests/unit/test_tasklets.py

Probably not super useful, but at least we're backwards compatible.

Implement ``tasklets.toplevel``.

---

src/google/cloud/ndb/_datastore_api.py
src/google/cloud/ndb/model.py
tests/system/test_crud.py
tests/unit/test_model.py

Legacy NDB enforced that only naive datetimes could be set for a
DateTime property and it always returned naive datetimes.
This adds a validation exception if the user tries to set a datetime
with a timezone on a DateTimeProperty and also strips datetimes of
``tzinfo`` as they're being read from Datastore, as Datastore adds the
UTC timezone to datetimes when reading out from the database.
Fixes #165.

Enforce naive datetimes for ``DateTimeProperty``.

---

tests/unit/test_model.py

Following up on this note from Danny: "Model._equivalent doesn't have
checks that properties are the same (only can happen for an Expando) and
a check for property names with a . (only can happy with a
StructuredProperty) (added in #6695)"
After looking at this, while the original Legacy code had code
specifically to deal with these cases, it doesn't appear to be
necessary. Tests for equality work fine even without explicit code for
Expando and StructuredProperty. Added tests prove this is the case.

 Some additional tests for Model.__eq__()

---

google/cloud/ndb/client.py
google/cloud/ndb/context.py
google/cloud/ndb/model.py
tests/conftest.py
tests/system/conftest.py
tests/system/test_crud.py
tests/system/test_query.py
tests/unit/test_model.py

The NDB rewrite, when storing values for structured properties, has been taking advantage of the native Datastore capability to arbitrarily nest entities as property values. Data written using the new NDB, however, would not be compatible with the legacy (Python 2) version, which always only stores a single entity in Datastore, using dotted property names to store the values of structured properties.
This patch introduces a new context flag, ``legacy_data``, which, when ``True``, causes NDB to store data in such a way as to be backwards compatible with the old version. The flag is ``True`` by default, requiring users to make a conscious decision to break backwards compatibility.
Fixes #178

Store Structured Properties in backwards compatible way

---

google/cloud/ndb/model.py
tests/system/test_crud.py

Use correct class when deserializing a PolyModel entity.

---

google/cloud/ndb/_remote.py
google/cloud/ndb/exceptions.py
google/cloud/ndb/tasklets.py
tests/system/test_query.py
tests/unit/test__remote.py
tests/unit/test_tasklets.py

This brings our implementation of ``Future`` in parity with the
``Future`` interface defined in the Python 3 standard library, and makes
it possible to cancel asynchronous ``grpc`` calls from NDB.

Implement ``Future.cancel()``

---

google/cloud/ndb/_datastore_api.py
google/cloud/ndb/_datastore_query.py
google/cloud/ndb/_eventloop.py
google/cloud/ndb/context.py
google/cloud/ndb/tasklets.py
test_utils/scripts/get_target_packages.py
test_utils/test_utils/scripts/get_target_packages.py
tests/unit/test_model.py

Found with:
```
codespell --version
1.14.0
```

Spelling fixes.

---

MIGRATION_NOTES.md

This typo was leading users astray.

Fix typo in MIGRATION_NOTES.md

---

google/cloud/ndb/client.py
tests/unit/test_client.py

Fixes #213. At the end of ``Client.context()`` there's a call to
``context.eventloop.run()`` that used to flush the event queue and
finish any unfinished business on the loop before exiting the context.
Due to an indentation error this call was not occurring with the context
active, so you could get a ``ContextError`` in any handlers run at this
time. This fixes that error.

Finish unfinished business in context.

---

MIGRATION_NOTES.md
google/cloud/ndb/query.py
tests/system/test_query.py
tests/unit/test_query.py

Fixes #210 .
A couple of features didn't come along with this implementation:
1) The `pass_batch_into_callback` argument: This wouldn't make a lot of sense in a query that uses an in-memory post filter and is impossible to do in MultiQuery (a logical query that merges the results of more than one Datastore query). While we could conceivably implement this in the case where a query maps directly onto a Datastore query, the details of the batching seem like an implementation detail that needn't really be exposed to the user. The utility of such a feature is uncertain, as well.
2) The `merge_future` argument: This seems to be difficult enough to use that it likely isn't being used. The uses cases it *seems* to be targeting could probably be better handled by adding some user friendly …

Implement ``Query.map`` and ``Query.map_async``.

---

google/cloud/ndb/model.py
tests/system/test_query.py
tests/unit/test_model.py

Binding parameters in `Model._gql` was broken due to a misplaced
parenthesis. Fixes #222.

Fix `Model._gql`.

---

google/cloud/ndb/client.py
google/cloud/ndb/context.py
tests/unit/test_client.py

When creating a top level context, check to make sure there isn't already a running context for this thread. This is an attempt to root a possible weird concurrency problem. Related to #182, but not a fix.

Check context

---

google/cloud/ndb/model.py
tests/system/test_crud.py
tests/unit/test_model.py

This was in the original code, but was overlooked when porting. Fixes #216

Implement ``_prepare_for_put`` for ``StructuredProperty`` and ``LocalStructuredProperty``.

---

tests/system/test_crud.py
tests/system/test_query.py

Make sure that `dispose_of` is called immediately after storing an
entity to make sure an error in the test doesn't prevent the entities
from getting cleaned up.

fix: Improve test cleanup.

---

google/cloud/ndb/_datastore_query.py
tests/system/test_query.py
tests/unit/test__datastore_query.py

Fixes #236. It was found that when a result set spanned multiple
batches, we weren't updating `limit` and `offset` on subsequent queries.
Now we do.

fix: Correctly handle `limit` and `offset` when batching query results.

---

google/cloud/ndb/model.py
google/cloud/ndb/utils.py
tests/system/test_crud.py

The changes for Python 2.7 compatibility broke the constructor for
KeyProperty, making it so you could no longer pass in a string for the
`kind` argument as a keyword. This reverts back to something more like
what was used in the original version of NDB, but preserving the
documented method signature.
I'm not a huge fan of this style of argument handling. (Maybe the first
argument is `name`, or maybe it's `kind`, let's figure it out!) But I
guess we're stuck with it for backwards compatibility.
Thanks to @epluntze for pointing me in the right direction.
Fixes #240.

Fix argument handling for `KeyProperty` constructor.

---

tests/unit/test__datastore_query.py

A unit test was relying on a call to `dict.keys()` to return keys in a
specific order. Strangely this test never failed for us, but was
reported by @simonff.
Fixes #244.

Fix unstable order bug in unit test.

---

google/cloud/ndb/model.py
tests/system/index.yaml
tests/system/test_query.py
tests/unit/test_model.py

This fixes issues, generally, with the handling of repeated properties
with projection queries, but also specifically for the "class" property
of PolyModel entities.
Fixes #248

Fix handling of repeated properties with projection queries.

---

google/cloud/ndb/model.py
tests/unit/test_model.py

fix: IntegerProperty now accepts `long` type for Python 2.7.

---

google/cloud/ndb/_gql.py
google/cloud/ndb/query.py
tests/system/test_query.py
tests/unit/test__gql.py
tests/unit/test_query.py

It turns out that `query.ParameterizedFunction` wasn't finished in its
implementation. It is meant to deal with the case, in GQL, where GQL
functions are called.
This PR also adds an implementation for the `LIST` GQL function and
stubs for future implementations of `USER` and `KEY`. Remaining GQL
functions needing to be implemented are unknown at this time.
Fixes #258.

Finish implementation of `query.ParameterizedFunction`.

---

docs/global_cache.rst

Small fix for the global cache documentation, which appears in the table of contents as "Context".
See https://googleapis.dev/python/python-ndb/latest/global_cache.html

Fixes the page title for the global cache documentation.

---

google/cloud/ndb/model.py
tests/unit/test_model.py

If LocalStructureProperty contains other Structured/LocalStructured Properties, the created model must be returned from the _validate(self, value) function.
This mirrors exactly how this is done in StructuredProperty._validate()

Fix #273 : Local Structured Property population via .populate(**kwargs)

---

docs/conf.py
google/cloud/ndb/_datastore_query.py
google/cloud/ndb/key.py
google/cloud/ndb/model.py
google/cloud/ndb/query.py
tests/unit/test_key.py
tests/unit/test_model.py
tests/unit/test_query.py

Removed unnecessary `_datastore_query._Result.__ne__` since
`functools.total_ordering` defines it from `__eq__`.
Added `key.Key.__ne__` from App Engine NDB for Python 2 compatibility.
Added `model._NotEqualMixin` from App Engine NDB and used it in
`model.IndexProperty`, `model.Index`, `model.IndexState`,
`model._BaseValue` and `model.Model` for Python 2 compatibility.
Added `query.Node.__ne__` from App Engine NDB so that it is used by
all subclasses and removed unnecessary `query.FilterNode.__ne__`.

fix: fix missing __ne__ methods

---

noxfile.py

We don't claim to support pypy at this time.

Remove pypy from tests run by nox.

---

google/cloud/ndb/model.py
tests/system/test_query.py
tests/unit/test_model.py

In Datastore, projection queries involving entities with DateTime
properties return integer timestamps instead of `datetime.datetime`
objects. This fix handles that case and returns `datetime.datetime`
objects regardless of the query type.
Fixes #261.

fix: Handle `int` for DateTimeProperty

---

google/cloud/ndb/model.py
tests/system/test_crud.py

See comments in code for design considerations. This is a compromise
solution.
Fixes #284.

fix: Convert NDB keys to Datastore keys for serialization.

---

google/cloud/ndb/_datastore_query.py
tests/unit/test__datastore_query.py

In an overabundance of caution, we were deleting `cursor_after` from
QueryIterator after exhausting the iterator. This was found to differ
from the original implementation, however, and break some customer's
code.
Fixes #292

fix: Preserve `QueryIterator.cursor_after`.

---

google/cloud/ndb/query.py
tests/system/test_query.py
tests/unit/test_query.py

The query.fetch method accepts query options, and passed them intact to the datastore query. If a projection argument containing model.Porperty objects was passed they weren't converted to strings, causing an error. Fixed that.

Fetch projection

---

google/cloud/ndb/model.py
tests/system/test_crud.py
tests/unit/test_model.py

This never actually worked.
Fixes #280

fix: Finish implementation of UserProperty.

---

google/cloud/ndb/model.py
tests/system/test_misc.py
tests/unit/test_model.py

fix: Don't set key on structured property entities.

---

google/cloud/ndb/_batch.py
google/cloud/ndb/_cache.py
google/cloud/ndb/_datastore_api.py
tests/system/conftest.py
tests/system/test_crud.py
tests/unit/test__batch.py
tests/unit/test__cache.py
tests/unit/test__datastore_api.py

fix: use multiple batches of limited size for large operations

---

tests/pytest.ini
tests/system/__init__.py
tests/system/conftest.py
tests/system/test_query.py

We have been having more transient errors in the system tests run by
Kokoro. This patch:
1) Increased timeout used by `eventually` fixture from 60 seconds to 120
seconds.
2) Randomizes "other namespace", like we were already doing with the
primary namespace used by tests. This should make it vanishingly
unlikely that a test can have its initial state polluted by a previously
run test, as each test will be run in its own namespace.
3) Relaxes the checks for undeleted entities during test cleanup.
Instead of a failing assertion, now, we'll just log a warning if there
are any leftover entities at the end of a test.

fix: attempt to have fewer transient errors in continuous integration

---

google/cloud/ndb/_datastore_types.py
google/cloud/ndb/_eventloop.py
google/cloud/ndb/blobstore.py
google/cloud/ndb/context.py
google/cloud/ndb/django_middleware.py
google/cloud/ndb/key.py
google/cloud/ndb/metadata.py
google/cloud/ndb/model.py
google/cloud/ndb/msgprop.py
google/cloud/ndb/query.py
google/cloud/ndb/stats.py
google/cloud/ndb/tasklets.py
tests/system/test_misc.py

In Python 2.7, classes which use `__slots__` can't be pickled. Users
have reported problems trying to pickle NDB entities, indicating there
is some perceived use case for pickling entities.
Fixes #311

fix: disuse `__slots__` in most places

---

google/cloud/ndb/_datastore_api.py
google/cloud/ndb/_transaction.py
tests/system/test_crud.py
tests/unit/test__datastore_api.py

This fixes a bug that caused deleting an entity inside of a transaction
to hang.
Fixes #271

fix: fix delete in transaction

---

google/cloud/ndb/key.py
google/cloud/ndb/model.py
tests/system/test_query.py

fix: make sure ``key.Key`` uses namespace from client when not specified

---

google/cloud/ndb/model.py
noxfile.py
tests/system/test_crud.py
tests/unit/test_model.py

Way back in PR #35 (a fix for #32), I accidentally disabled support for passing `compressed=True` to `TextProperty`. Because #35 involved refactoring `TextProperty` so that it no longer inherited from `BlobProperty`, the older version of `TextProperty` needed to be brought back and has now become `CompressedTextProperty`, which will store text properties as UTF-8 compressed blobs, as was the case with GAE NDB. I've overridden `__new__` for `TextProperty` so I can substitute `CompressedTextProperty` for `TextProperty` when `compressed=True` is passed.
Fixes #277

fix: resurrect support for compressed text property

---

google/cloud/ndb/model.py
tests/system/test_crud.py
tests/unit/test_model.py

Legacy ndb is not able to read back serialized entities when using repeated LocalStructuredProperty. This fix saves those entities without serialization when legacy data is set in the context (default behavior)

fix: allow legacy ndb to read LocalStructuredProperty entities.

---

google/cloud/ndb/key.py
tests/unit/test_key.py

Workaround the fact that Google has deprecated the location prefix, but it is still required by the Google Datastore admin console, by allowing users to manually provide a location prefix when generating urlsafe keys.
Fixes #264.

feat: `Key.to_legacy_urlsafe()`

---

google/cloud/ndb/tasklets.py
tests/system/test_misc.py
tests/unit/test_tasklets.py

`yield` of an empty list will no longer cause a tasklet to hang forever.
Fixes #353.

fix: fix bug with `yield` of empty list in tasklets

---

google/cloud/ndb/tasklets.py
tests/system/test_crud.py
tests/unit/test_tasklets.py

This adds backwards compatibility with the legacy code.
Fixes #357.

fix: support nested sequences in parallel `yield` for tasklets

---

google/cloud/ndb/_datastore_api.py
google/cloud/ndb/client.py
google/cloud/ndb/context.py
google/cloud/ndb/key.py
google/cloud/ndb/model.py
tests/conftest.py
tests/unit/test__datastore_api.py
tests/unit/test_context.py

This brings our practice in line with `google.cloud.datastore`, which
also creates one channel per client. This works around a resource leak issue
by not requiring the channel to clean up after itself properly in normal
usage. The root cause of that issue seems to lie somewhere in
`google.auth`, which is where I will follow up.
Fixes #343

fix: move stub (grpc communication channel) to client

---

google/cloud/ndb/model.py
tests/system/test_query.py
tests/unit/test_model.py

For `JsonProperty`, even though we write and normally read `bytes`, when
retrieving a `JsonProperty` in a projection query, for some reason, we
get an already decoded string, which cause NDB to file with projection
queries that read JSON properties.
Fixes #378

fix: accept `bytes` or `str` as base value for `JsonProperty`

---

google/cloud/ndb/_transaction.py
tests/system/test_misc.py
tests/unit/test__transaction.py

`ndb.transction` now accepts a boolean argument, `join`, which
determines behavior when called in the context of an already running
transaction. If `join` is `True`, the already running transaction is
used, otherwise an exception is raises, as before.
For `transaction` and `transaction_async`, the default for `join` is
`False`, so passing nothing retains the old behavior. For the
`transactional`, `transactional_async`, and `transactional_tasklet`
decorators the default for `join` is `True`, which makes the functions
decorated with these composable, by default. This means a decorated
function can call another decorated function and the second call will
just use the already running transaction.
Closes #366

feat: new `join` argument for `transaction` and related functions

---

google/cloud/ndb/client.py
google/cloud/ndb/context.py
google/cloud/ndb/key.py
google/cloud/ndb/model.py
google/cloud/ndb/query.py
tests/system/conftest.py
tests/unit/test_context.py

It is now possible to set the namespace on the context, overriding the
namespace set on the client. This makes it easier to write multi-homed
applications which might access different namespaces depending on which
user is logged in or other variable only known at request time.
`client.Client.context` has a new argument, `namespace`, which can be
used to set the namespace at request time. Here is an example of you
might do this in a WSGI middleware:
~~~~
def ndb_wsgi_middleware(wsgi_app):
client = ndb.Client()
def middleware(environ, start_response):
global_cache = ndb.RedisCache.from_environment()
namespace = get_namespace_from_request(environ)
with client.context(global_cache=global_cache, namespace=namespace):
return wsgi_app(environ, start_response)
return middleware
app = …

feat: add `namespace` property to `context.Context`

---

google/cloud/ndb/_retry.py
tests/unit/test__retry.py

fix: Add `ABORTED` to retryable status codes.

---

google/cloud/ndb/_options.py
tests/system/test_misc.py
tests/unit/test__datastore_api.py

Fixes a bug where reads during a transaction wouldn't necessarily happen
in the context of the transaction.
Fixes #394

fix: make sure reads happen in transaction if there is a transaction

---

google/cloud/ndb/_datastore_query.py
tests/unit/test__datastore_query.py

For some queries, when paging through batches of results, Firestore will
return a batch that has no results, even though there are still results
left to return for the query. Previously, this would cause
`QueryIterator` to prematurely stop iterating over results. Empty
batches are now handled and skipped so that `QueryIterator` doesn't stop
retrieving results prematurely.
Fixes #386

fix: handle empty batches from Firestore

---

google/cloud/ndb/_datastore_query.py
tests/system/test_query.py
tests/unit/test__datastore_query.py

Fixes a bug where we blithely assumed that if we sent
Datastore/Firestore a query with an offset, that the first batch returned
would skip the entire offset. In practice, for high offsets, it's possible
for Datastore/Firestore to return a results batch that is empty and
which has `skipped_results` set to some number less than the value of
`offset` that we sent it. In this case, we still need to send a value
for `offset` when retreiving the next batch. This patch uses
`skipped_results` to compute a new `offset` for the follow up batch.
Fixes #392

fix: use `skipped_results` from query results to adjust offset

---

google/cloud/ndb/query.py
tests/unit/test_query.py

@gaborfeher pointed at that while we were trying to use a `keys_only`
query for `Query.count()` we were failing to actually do so. This is
@gaborfeher's proposed fix from PR #400, fleshed out with unit tests.
Fixes #404.

fix: use true `keys_only` query for `Query.count()`

---

google/cloud/ndb/_transaction.py
tests/system/test_crud.py
tests/system/test_misc.py
tests/unit/test__transaction.py

In order to enforce transactional integrity, the context cache can't be shared
across transactions.
Fixes #394 (again)

fix: use fresh context cache for each transaction

---

google/cloud/ndb/_transaction.py
tests/system/test_misc.py

When a transaction fails, clear the local context cache for the
transaction to prevent leaking inconsistent data.
Fixes #398

fix: clear context cache on rollback

---

.kokoro/build.sh
.kokoro/publish-docs.sh
.kokoro/release.sh

This basically just merges the changes from #393, except it does not destroy our redis config. Turns out the spellcheck setup was duplicated, so it's OK to remove it.

build: integrate changes from autosynth PR

---

google/cloud/ndb/_retry.py
tests/unit/test__retry.py

In `_retry.is_transient_error`, we now check to make sure the exception
is an instance of `grpc.Call` before examining its `code` attribute. We
also make sure `code` is callable before calling it.
Fixes #415

fix: don't rely on duck typing for `_retry.is_transient_error`

---

google/cloud/ndb/query.py
tests/unit/test_model.py
tests/unit/test_query.py

The `projection` argument is now handled the same whether it is passed
in to the constructor for `Query` or to one if it's methods, such as
`Query.fetch`.
Fixes #379

fix: uniform handling of `projection` argument

---

google/cloud/ndb/_batch.py
google/cloud/ndb/_datastore_api.py
google/cloud/ndb/_eventloop.py
google/cloud/ndb/_transaction.py
google/cloud/ndb/tasklets.py
tests/system/__init__.py
tests/system/test_crud.py
tests/system/test_misc.py
tests/system/test_query.py
tests/unit/test__datastore_api.py
tests/unit/test__eventloop.py
tests/unit/test__transaction.py
tests/unit/test_tasklets.py

Referring to issue #426, the problem ultimately turned out to be that
we could fall out of the transaction scope and trigger a commit while
there is still work left queued on the event loop, including, in this
case, the tasklet that would eventually schedule the call to delete,
causing the delete to never actually happen.
The fix is to go ahead and consume the event loop queues before
scheduling the call to COMMIT. However, if there are other tasks
happening in parallel, this can really mess with the natural sequence of
events in ways that can cause things to blow up. (All of the
`parallel_transaction` tests in `tests/system/test_misc.py` for
instance, will fail.) The fix for that is to give each transaction its
own event loop, so that when it calls `_eventloop.run` prior to commit,
it is …

fix: refactor transactions to use their own event loops

---

google/cloud/ndb/model.py
tests/system/test_query.py
tests/unit/test_model.py

Restores a linear search for subproperty by Python name if different
from datastore name, when getting subproperties in
`StructuredProperty.__getattr__`. This bit of code just got overlooked when
porting from legacy.
Fixes #449

fix: respect `_code_name` in `StructuredProperty.__getattr__`

---

google/cloud/ndb/_datastore_query.py
google/cloud/ndb/context.py
tests/system/test_crud.py
tests/unit/test__datastore_query.py

We were returning cache values in some cases and not others, generating some confusion.
Refs #441

fix: all query types should use cache if available

---

google/cloud/ndb/_datastore_api.py
google/cloud/ndb/_retry.py
tests/system/test_query.py
tests/unit/test__datastore_api.py
tests/unit/test__retry.py

This brings NDB into line with other API libraries by calling
`google.api_core.exceptions.from_grpc_error` to convert grpc errors to
distinct exceptions from `google.api_core.exceptions`.
Closes #416

feat: convert grpc errors to api core exceptions

---

google/cloud/ndb/__init__.py
google/cloud/ndb/_datastore_api.py
google/cloud/ndb/_eventloop.py
google/cloud/ndb/_remote.py
google/cloud/ndb/context.py
tests/unit/test__eventloop.py
tests/unit/test_context.py

Two new attributes have been added to the top level context object,
which can be used in looking at performance of underlying Datastore
calls. `rpc_time` records the total amount of time all rpc calls made
in that context have taken. `wait_time` records the total amount of time
spent waiting (blocking) for rpc calls to complete. Because of
parallelism, `wait_time` should be less than `rpc_time`, although in
practice they're almost always quite close.

feat: record time spent waiting on rpc calls

---

google/cloud/ndb/_cache.py
tests/system/test_misc.py
tests/unit/test__cache.py

fix: do not disclose cache contents in stack traces

---

google/cloud/ndb/key.py
tests/unit/test_key.py

fix: include ancestors in `Key.to_legacy_urlsafe`

---

google/cloud/ndb/_cache.py
google/cloud/ndb/key.py
tests/unit/test__datastore_query.py

`Key.__hash__` is relatively expensive to compute, so the computed hash
is now stored on the `Key` instance on the first call to `Key.__hash__`.
`context.ContextCache` has been made a subclass of `dict` rather than
`UserDict`, resulting in *much* better performance.

perf: improve context cache performance

---

google/cloud/ndb/model.py
tests/system/test_crud.py
tests/unit/test_model.py

fix: support polymodel in local structured property

---

google/cloud/ndb/context.py
setup.py

feat: use contextvars.ConvextVar instead of threading.local in Python 3

---

google/cloud/ndb/_datastore_api.py
google/cloud/ndb/_datastore_query.py
google/cloud/ndb/_eventloop.py
google/cloud/ndb/_transaction.py
google/cloud/ndb/utils.py
tests/unit/test_utils.py

In order to enable debug logging, users must now set an environment
variable, `NDB_DEBUG`, to a "truthy" value (True, t, Yes, 1, etc...).
This mostly prevents gRPC protocol buffers from getting rendered as
strings unnecessarily, which has a significant impact on performance.

perf: suppress debug logging in normal operation

---

google/cloud/ndb/_datastore_query.py
tests/system/index.yaml
tests/system/test_query.py
tests/unit/test__datastore_query.py

Since the result sets for multiqueries have to be merged, if a
projection is specified, make sure the projection used for the
underlying Datstore queries includes any properties we need for a sorted
merge.
Fixes #509.

fix: transparently add sort properties to projection for multiqueries

---

google/cloud/ndb/utils.py
tests/conftest.py

Changes introduced in #508 caused debug logging to break. The bug is
fixed and debug logging is now turned on during testing, so we can catch
regressions.

fix: fix format exceptions in `utils.logging_debug`

---

google/cloud/ndb/_datastore_query.py
google/cloud/ndb/query.py
tests/unit/test__datastore_query.py
tests/unit/test_query.py

For simple queries (queries that map directly to single Datastore
queries, ie not multiqueries, or queries with post filters),
`Query.count` can be otimized by setting a high offset and counting the
number of entities skipped.
Note that this still requires Datastore to assemble and iterate over a
result set and Datastore will still only "skip" a certain number of
entities at a time. (1000 at the time of this writing.) So this doesn't
dramatically impact the amount of work that has to be done on the
Datastore side, nor does it reduce the number gRPC calls necessary to
count a large result set. It does reduce significantly, however, the amount of
I/O required, which has sped up some large counts in testing by a factor
of around 4x.

perf: improve count query performance for simple queries

---

google/cloud/ndb/_datastore_query.py
tests/system/test_query.py
tests/unit/test__datastore_query.py

fix: make sure `keys_only` ordered multiquery returns keys not entities

---

google/cloud/ndb/_datastore_query.py
tests/unit/test__datastore_query.py

The emulator is different enough from the real Datastore to require some
special handling.
Fixes #525

fix: make optimized `Query.count()` work with the datastore emulator

---

.kokoro/build.sh
.kokoro/docker/docs/Dockerfile
docs/conf.py
google/cloud/ndb/__init__.py
google/cloud/ndb/global_cache.py
setup.py
tests/system/conftest.py
tests/system/test_crud.py
tests/unit/test_global_cache.py

Mostly just still need to test.

feat: memcached integration

---

google/cloud/ndb/metadata.py
google/cloud/ndb/model.py
tests/system/test_crud.py
tests/unit/test_metadata.py
tests/unit/test_model.py

when passed in when context is using another namespace.
refs #535

fix: get_by_id and get_or_insert should use default namespace

---

google/cloud/ndb/_datastore_api.py
tests/system/test_misc.py

fix: `@non_transactional` decorator was not working correctly with async

---

setup.py

there are breaking changes in the next major version of datastore and pinning below 2.0.0 will stop those changes from breaking ndb.
Fixes #568

fix(dependencies): Pin to less than 2.0.0 for google-cloud-datastore

---

google/cloud/ndb/_datastore_query.py
tests/unit/test__datastore_query.py

fix: support empty not_finished messages that cause query.count() to return early

---

google/cloud/ndb/query.py
tests/system/test_query.py
tests/unit/test_query.py

fix: return a tuple when empty result returned on query

---

google/cloud/ndb/_datastore_query.py
google/cloud/ndb/client.py
tests/unit/test__datastore_query.py

This my proposed fix for: #584
The idea is to store a boolean to remember the type of the backend (emulator or real) during the whole life of the client. I am not super happy about this but I think it's still an improvement over the current way things work. There is already branching in the code based on the type of the backend, but it's basically a guesswork based on the behavior of the backend. And that seems to be fragile, just like my issues demonstrate. After this PR, the branching would be made explicit, based on the actual backend type. 
An interesting side-effect of this change is that the change in line 181 actually also fixes #575 on my data, because the backend in my case doesn't send back an empty batch if the correct cursor is used in the query. However, based on #386 the …

Clean up datastore emulator workarounds

---

google/cloud/ndb/global_cache.py

Had mistakenly written that non-strict behavior occurs when
`strict_read` or `strict_write` are `True`, when it should have said
when they are `False`.
Closes #563.

docs: correct documentation for `GlobalCache`

---

google/cloud/ndb/_legacy_protocol_buffer.py
tests/unit/test__legacy_entity_pb.py

The code in this library does not match that of the original GAE
runtime, which will do 2's complemenet math when deserializing signed
integers.
Legacy code reference: https://github.com/GoogleCloudPlatform/python-compat-runtime/blob/743ade7e1350c790c4aaa48dd2c0893d06d80cee/appengine-compat/exported_appengine_sdk/google/net/proto/ProtocolBuffer.py#L743-L747
Fixes #590

fix: handle negatives in protobuf deserialization

---

google/cloud/ndb/_datastore_api.py
google/cloud/ndb/_retry.py
google/cloud/ndb/_transaction.py
google/cloud/ndb/context.py
google/cloud/ndb/exceptions.py
tests/unit/test__retry.py

fix: make nested retry blocks work for RPC calls

---

google/cloud/ndb/_cache.py
google/cloud/ndb/global_cache.py
tests/unit/test__cache.py

When an operation on the global cache is tried and there is a transient
error, such as not being able to connect to a Redis or Memcached server,
if the operation is being tried in strict mode, then the operation is
now retried a number of times before the transient error is eventually
raised to the application layer.
Implements #601

feat: retry global cache operations on transient errors

---

tests/unit/test__retry.py

fix: mock call to `tasklets.sleep` in unit test

---

google/cloud/ndb/model.py
tests/system/test_crud.py
tests/unit/test_model.py

There was a bug when using a compressed blob property as a child of a structured
property while using the legacy data format for structured properties.
Fixes #602

fix: fix bug with compressed blob property

---

google/cloud/ndb/model.py
tests/unit/test_model.py

This had been in the original NDB but didn't make it into the port for
some reason. It's needed so that an instance's properties can change
without affecting the class's properties. This is mostly for `Expando`,
but also for unpickling.
Fixes #566

fix: reimplement `_clone_properties`

---

google/cloud/ndb/_datastore_query.py
tests/system/test_query.py
tests/unit/test__datastore_query.py

Corrects the issue pointed out in #586, that we weren't doing the right
thing for deleted entities. Also corrects an issue noticed while fixing
that, where the cache wasn't being updated with entities from queries.
Behavior should now match legacy in both these regards.
Fixes #586

fix: replicate legacy behavior for using cache with queries

---

google/cloud/ndb/key.py
google/cloud/ndb/query.py
tests/system/test_query.py
tests/unit/test_key.py
tests/unit/test_query.py

Also fixes bug that was discovered while working this where keys weren't properly inheriting the namespace of their parent.
Fixes #577

fix: prevent mismatch error when using default namespace on ancestor queries

---

google/cloud/ndb/model.py
tests/system/test_misc.py
tests/unit/test_model.py

fix: support `int` as base type for `BooleanProperty`
